#!/usr/bin/env php
<?php
date_default_timezone_set('Europe/Prague');

require __DIR__ . '/vendor/autoload.php';
require __DIR__  . '/EventFetchCommand.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new EventFetchCommand());

$application->run();
